//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tests.CategoriesServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://epam.com/NorthwindService", ConfigurationName="CategoriesServiceReference.ICategoriesService")]
    public interface ICategoriesService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://epam.com/NorthwindService/ICategoriesService/GetCategoryNames", ReplyAction="http://epam.com/NorthwindService/ICategoriesService/GetCategoryNamesResponse")]
        System.Collections.Generic.List<string> GetCategoryNames();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://epam.com/NorthwindService/ICategoriesService/GetCategoryImage", ReplyAction="http://epam.com/NorthwindService/ICategoriesService/GetCategoryImageResponse")]
        System.IO.Stream GetCategoryImage(string categoryName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://epam.com/NorthwindService/ICategoriesService/SaveCategoryImage", ReplyAction="http://epam.com/NorthwindService/ICategoriesService/SaveCategoryImageResponse")]
        void SaveCategoryImage(System.IO.Stream categoryImage);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICategoriesServiceChannel : Tests.CategoriesServiceReference.ICategoriesService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CategoriesServiceClient : System.ServiceModel.ClientBase<Tests.CategoriesServiceReference.ICategoriesService>, Tests.CategoriesServiceReference.ICategoriesService {
        
        public CategoriesServiceClient() {
        }
        
        public CategoriesServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CategoriesServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CategoriesServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CategoriesServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<string> GetCategoryNames() {
            return base.Channel.GetCategoryNames();
        }
        
        public System.IO.Stream GetCategoryImage(string categoryName) {
            return base.Channel.GetCategoryImage(categoryName);
        }
        
        public void SaveCategoryImage(System.IO.Stream categoryImage) {
            base.Channel.SaveCategoryImage(categoryImage);
        }
    }
}
