//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tests.CategoriesServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CategoriesServiceReference.ICategoriesService")]
    public interface ICategoriesService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICategoriesService/GetCategoryNames", ReplyAction="http://tempuri.org/ICategoriesService/GetCategoryNamesResponse")]
        System.Collections.Generic.List<string> GetCategoryNames();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICategoriesServiceChannel : Tests.CategoriesServiceReference.ICategoriesService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CategoriesServiceClient : System.ServiceModel.ClientBase<Tests.CategoriesServiceReference.ICategoriesService>, Tests.CategoriesServiceReference.ICategoriesService {
        
        public CategoriesServiceClient() {
        }
        
        public CategoriesServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CategoriesServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CategoriesServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CategoriesServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<string> GetCategoryNames() {
            return base.Channel.GetCategoryNames();
        }
    }
}
